#pragma once
#include <string>
using namespace std;

#define DOTLIB_FONT_CHARINT_ONE 29
#define DOTLIB_FONT_CHARINT_TWO 30
#define DOTLIB_FONT_CHARINT_THREE 31
#define DOTLIB_FONT_CHARINT_FOUR 32
#define DOTLIB_FONT_CHARINT_FIVE 33
#define DOTLIB_FONT_CHARINT_SIX 34
#define DOTLIB_FONT_CHARINT_SEVEN 35
#define DOTLIB_FONT_CHARINT_EIGHT 36
#define DOTLIB_FONT_CHARINT_NINE 37
#define DOTLIB_FONT_CHARINT_ZERO 38
#define DOTLIB_FONT_CHAR_SPACE 39
#define DOTLIB_FONT_CHAR_DOT 40
#define DOTLIB_FONT_CHAR_COMMA 41
#define DOTLIB_FONT_CHAR_EXCLAMATION 42

string DOTLIBRARY_FONT_DEFINITION[];